  alias: nPad bluetooth
  trigger:
    - platform: state
      entity_id: sensor.npad_bt_thuis
  action:
    service_template: >
      {% if states.sensor.npad_bt_thuis.state | float > 43 %}
         input_boolean.turn_on
      {% else %}
         input_boolean.turn_off
      {% endif %}
    entity_id: input_boolean.npad_bluetooth
