 ### Monitor
  bluetooth_trigger_blok:
    name: Bluetooth trigger blokkeren
    initial: off
    icon: mdi:bluetooth-off

  living_arrive:
  living_depart:
  keuken_arrive:
  keuken_depart:
  garage_arrive:
  garage_depart:

  gphone_bluetooth:
    name: gPhone bluetooth
    icon: mdi:bluetooth-connect

  bompa_bt_aanwezig:
    name: Bompa aanwezig
    icon: mdi:bluetooth-connect
  
  oma_bt_aanwezig:
    name: Oma aanwezig
    icon: mdi:bluetooth-connect

  forerunner_bluetooth:
    name: Forerunner bluetooth
    icon: mdi:bluetooth-connect
  
  mphone_bluetooth:
    name: mPhone bluetooth
    icon: mdi:bluetooth-connect
  
  npad_bluetooth:
    name: nPad bluetooth
    icon: mdi:bluetooth-connect
  
  fpad_bluetooth:
    name: fPad bluetooth
    icon: mdi:bluetooth-connect