  ### Homekit integration
  presence_licht_aan:
  koogeek_achterdeur:
  koogeek_voordeur:
  
  gielhomekit:
    name: Homekit
    icon: mdi:home-automation
  
  martinehomekit:
    name: Homekit
    icon: mdi:home-automation
  
###  Homekit 
  achterdeur_open:
  voordeur_open:
  spot_netatmo: