  - platform: switch
    name: Luster zithoek
    entity_id: switch.shelly_72_1_luster_zithoek

  - platform: switch
    name: Luster danszaal
    entity_id: switch.shelly_72_2_luster_danszaal
  
  - platform: switch
    name: Luster keuken
    entity_id: switch.shelly_70_1_keuken_luster

  - platform: switch
    name: Wc
    entity_id: switch.shelly_64_1_wc
  
  - platform: switch
    name: Spots danszaal
    entity_id: switch.shelly_64_2_spotjes_danszaal

  - platform: switch
    name: Badkamer hoog
    entity_id: switch.shelly_63_1_badkamer_hoog
  
  - platform: switch
    name: Badkamer pombak
    entity_id: switch.shelly_63_2_badkamer_pombak

  - platform: switch
    name: Gang beneden
    entity_id: switch.shelly_70_2_gang_beneden
  
  - platform: switch
    name: Gang boven
    entity_id: switch.shelly_71_1_gang_boven

  - platform: switch
    name: Slaapkamer hoog
    entity_id: switch.shelly_71_2_slaapkamer_hoog
  
  - platform: switch
    name: Inkom
    entity_id: switch.shelly_68_1_inkom

  - platform: switch
    name: Spots keuken
    entity_id: switch.shelly_68_2_spots_keuken
  
  - platform: switch
    name: Trap
    entity_id: switch.shelly_69_2_trap

  - platform: switch
    name: Waskot
    entity_id: switch.shelly_69_1_waskot
