# Bompa
- platform: mqtt
  state_topic: 'monitor/Keuken/bompa'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Bompa keuken'
  availability_topic: "monitor/Keuken/status"
  payload_available: "online"
  payload_not_available: "offline"
  json_attributes_topic: 'monitor/Keuken/bompa'

- platform: mqtt
  state_topic: 'monitor/Living/bompa'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Bompa living'
  availability_topic: "monitor/Living/status"
  payload_available: "online"
  payload_not_available: "offline"
  json_attributes_topic: 'monitor/Living/bompa'

- platform: mqtt
  state_topic: 'monitor/Garage/bompa'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Bompa garage'
  availability_topic: "monitor/Garage/status"
  payload_available: "online"
  payload_not_available: "offline"
  json_attributes_topic: 'monitor/Garage/bompa'

- platform: mqtt
  state_topic: 'monitor/tvPi/bompa'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Bompa tvPi'
  availability_topic: "monitor/tvPi/status"
  payload_available: "online"
  payload_not_available: "offline"
  json_attributes_topic: 'monitor/tvPi/bompa'

- platform: mqtt
  state_topic: 'monitor/Pi-Poortje/bompa'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Bompa PoortPi'
  availability_topic: "monitor/Pi-Poortje/status"
  payload_available: "online"
  payload_not_available: "offline"
  json_attributes_topic: 'monitor/Pi-Poortje/bompa'
