# gPhone
- platform: mqtt
  state_topic: 'monitor/Keuken/gphone'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'gPhone keuken'
  availability_topic: "monitor/Keuken/status"
  payload_available: "online"
  payload_not_available: "offline"
  json_attributes_topic: 'monitor/Keuken/gphone'

- platform: mqtt
  state_topic: 'monitor/Badkamer/gphone'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'gPhone badkamer'
  availability_topic: "monitor/Badkamer/status"
  payload_available: "online"
  payload_not_available: "offline"
  json_attributes_topic: 'monitor/Badkamer/gphone'

- platform: mqtt
  state_topic: 'monitor/Slaapkamer/gphone'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'gPhone slaapkamer'
  availability_topic: "monitor/Slaapkamer/status"
  payload_available: "online"
  payload_not_available: "offline"
  json_attributes_topic: 'monitor/Slaapkamer/gphone'

- platform: mqtt
  state_topic: 'monitor/Living/gphone'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'gPhone living'
  availability_topic: "monitor/Living/status"
  payload_available: "online"
  payload_not_available: "offline"
  json_attributes_topic: 'monitor/Living/gphone'

- platform: mqtt
  state_topic: 'monitor/Garage/gphone'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'gPhone garage'
  availability_topic: "monitor/Garage/status"
  payload_available: "online"
  payload_not_available: "offline"
  json_attributes_topic: 'monitor/Garage/gphone'

- platform: mqtt
  state_topic: 'monitor/tvPi/gphone'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'gPhone tvPi'
  availability_topic: "monitor/tvPi/status"
  payload_available: "online"
  payload_not_available: "offline"
  json_attributes_topic: 'monitor/tvPi/gphone'

- platform: mqtt
  state_topic: 'monitor/Pi-Poortje/gphone'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'gPhone PoortPi'
  availability_topic: "monitor/Pi-Poortje/status"
  payload_available: "online"
  payload_not_available: "offline"
  json_attributes_topic: 'monitor/Pi-Poortje/gphone'


# Forerunner
# - platform: mqtt
#   state_topic: 'monitor/Keuken/FD:BE:FE:17:E4:83'
#   value_template: '{{ value_json.confidence }}'
#   unit_of_measurement: '%'
#   name: 'Forerunner keuken'
#   availability_topic: "monitor/Keuken/status"
#   payload_available: "online"
#   payload_not_available: "offline"
#   json_attributes_topic: 'monitor/Keuken/FD:BE:FE:17:E4:83'

# - platform: mqtt
#   state_topic: 'monitor/Living/FD:BE:FE:17:E4:83'
#   value_template: '{{ value_json.confidence }}'
#   unit_of_measurement: '%'
#   name: 'Forerunner living'
#   availability_topic: "monitor/Living/status"
#   payload_available: "online"
#   payload_not_available: "offline"
#   json_attributes_topic: 'monitor/Living/FD:BE:FE:17:E4:83'

# - platform: mqtt
#   state_topic: 'monitor/Garage/FD:BE:FE:17:E4:83'
#   value_template: '{{ value_json.confidence }}'
#   unit_of_measurement: '%'
#   name: 'Forerunner garage'
#   availability_topic: "monitor/Garage/status"
#   payload_available: "online"
#   payload_not_available: "offline"
#   json_attributes_topic: 'monitor/Garage/FD:BE:FE:17:E4:83'
#   json_attributes_topic: 'monitor/Garage/FD:BE:FE:17:E4:83'
