# Oma
- platform: mqtt
  state_topic: 'monitor/Keuken/oma'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Oma keuken'
  availability_topic: "monitor/Keuken/status"
  payload_available: "online"
  payload_not_available: "offline"
  json_attributes_topic: 'monitor/Keuken/oma'

- platform: mqtt
  state_topic: 'monitor/Badkamer/oma'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Oma badkamer'
  availability_topic: "monitor/Badkamer/status"
  payload_available: "online"
  payload_not_available: "offline"
  json_attributes_topic: 'monitor/Badkamer/oma'

- platform: mqtt
  state_topic: 'monitor/Slaapkamer/oma'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Oma slaapkamer'
  availability_topic: "monitor/Slaapkamer/status"
  payload_available: "online"
  payload_not_available: "offline"
  json_attributes_topic: 'monitor/Slaapkamer/oma'

- platform: mqtt
  state_topic: 'monitor/Living/oma'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Oma living'
  availability_topic: "monitor/Living/status"
  payload_available: "online"
  payload_not_available: "offline"
  json_attributes_topic: 'monitor/Living/oma'

- platform: mqtt
  state_topic: 'monitor/Garage/oma'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Oma garage'
  availability_topic: "monitor/Garage/status"
  payload_available: "online"
  payload_not_available: "offline"
  json_attributes_topic: 'monitor/Garage/oma'

- platform: mqtt
  state_topic: 'monitor/tvPi/oma'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Oma tvPi'
  availability_topic: "monitor/tvPi/status"
  payload_available: "online"
  payload_not_available: "offline"
  json_attributes_topic: 'monitor/tvPi/oma'

- platform: mqtt
  state_topic: 'monitor/Pi-Poortje/oma'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Oma PoortPi'
  availability_topic: "monitor/Pi-Poortje/status"
  payload_available: "online"
  payload_not_available: "offline"
  json_attributes_topic: 'monitor/Pi-Poortje/oma'
