###  Smappee  ###
- platform: mqtt
  state_topic: 'servicelocation/576a42cf-d672-11e7-ac58-022d286959f5/realtime'
  value_template: "{{ value_json['voltages'][0]['voltage'] }}"
  unit_of_measurement: 'V'
  icon: mdi:gauge
  name: 'Spanning'

- platform: mqtt
  state_topic: 'servicelocation/576a42cf-d672-11e7-ac58-022d286959f5/realtime'
  value_template: '{{ value_json.totalPower }}'
  unit_of_measurement: 'W'
  icon: mdi:power-plug
  name: 'Huidig verbruik'

- platform: mqtt
  state_topic: 'servicelocation/576a42cf-d672-11e7-ac58-022d286959f5/realtime'
  value_template: "{{ value_json['channelPowers'][0]['power'] }}"
  unit_of_measurement: 'W'
  icon: mdi:power-plug
  name: 'Huidig verbruik L1'

- platform: mqtt
  state_topic: 'servicelocation/576a42cf-d672-11e7-ac58-022d286959f5/realtime'
  value_template: "{{ value_json['channelPowers'][1]['power'] }}"
  unit_of_measurement: 'W'
  icon: mdi:power-plug
  name: 'Huidig verbruik L2'

- platform: mqtt
  state_topic: 'servicelocation/576a42cf-d672-11e7-ac58-022d286959f5/realtime'
  value_template: "{{ value_json['channelPowers'][2]['power'] }}"
  unit_of_measurement: 'W'
  icon: mdi:power-plug
  name: 'Huidig verbruik L3'

- platform: template
  sensors:
    huidige_opbrengst:
      # state_topic: 'servicelocation/576a42cf-d672-11e7-ac58-022d286959f5/realtime'
      # value_template: "{{ value_json['channelPowers'][3]['power']  +  value_json['channelPowers'][4]['power']  +  value_json['channelPowers'][5]['power'] }}"
      value_template: >
        {% if (states('sensor.huidige_opbrengst_l1')  +  states('sensor.huidige_opbrengst_l2')  +  states('sensor.huidige_opbrengst_l3'))|int  < 0 %}
          0
        {% else %}
          {{ (states('sensor.huidige_opbrengst_l1'))|int  +  (states('sensor.huidige_opbrengst_l2'))|int  +  (states('sensor.huidige_opbrengst_l3'))|int }}  
        {% endif %}
      unit_of_measurement: 'W'
      icon_template: mdi:white-balance-sunny
      friendly_name: 'Huidige opbrengst'
      # {% if (value_json['channelPowers'][3]['power']  +  value_json['channelPowers'][4]['power']  +  value_json['channelPowers'][5]['power'])  < 0 %}
      #   0
      # {% else %}
      #   {{ value_json['channelPowers'][3]['power']  +  value_json['channelPowers'][4]['power']  +  value_json['channelPowers'][5]['power'] }}
      # {% endif %}

- platform: mqtt
  state_topic: 'servicelocation/576a42cf-d672-11e7-ac58-022d286959f5/realtime'
#   value_template: "{{ value_json['channelPowers'][3]['power'] }}"
  value_template: >
          {% if value_json['channelPowers'][3]['power']  < 0 %}
            0
          {% else %}
            {{ value_json['channelPowers'][3]['power'] }}
          {% endif %}
  unit_of_measurement: 'W'
  icon: mdi:white-balance-sunny
  name: 'Huidige opbrengst L1'

- platform: mqtt
  state_topic: 'servicelocation/576a42cf-d672-11e7-ac58-022d286959f5/realtime'
#   value_template: "{{ value_json['channelPowers'][4]['power'] }}"
  value_template: >
          {% if value_json['channelPowers'][4]['power']  < 0 %}
            0
          {% else %}
            {{ value_json['channelPowers'][4]['power'] }}
          {% endif %}
  unit_of_measurement: 'W'
  icon: mdi:white-balance-sunny
  name: 'Huidige opbrengst L2'

- platform: mqtt
  state_topic: 'servicelocation/576a42cf-d672-11e7-ac58-022d286959f5/realtime'
#   value_template: "{{ value_json['channelPowers'][5]['power'] }}"
  value_template: >
          {% if value_json['channelPowers'][5]['power']  < 0 %}
            0
          {% else %}
            {{ value_json['channelPowers'][5]['power'] }}
          {% endif %}
  unit_of_measurement: 'W'
  icon: mdi:white-balance-sunny
  name: 'Huidige opbrengst L3'

- platform: mqtt
  state_topic: 'servicelocation/576a42cf-d672-11e7-ac58-022d286959f5/aggregated'
  value_template: "{{ (value_json['intervalDatas'][0]['alwaysOn']) / 1000 }}"
  unit_of_measurement: 'Wh'
  icon: mdi:gauge
  name: 'Sluimerverbruik'

- platform: mqtt
  state_topic: 'servicelocation/576a42cf-d672-11e7-ac58-022d286959f5/aggregated'
  value_template: "{{ (value_json['intervalDatas'][0]['channelIntervalDatas'][0]['averagePowerfactor'] +
        value_json['intervalDatas'][0]['channelIntervalDatas'][1]['averagePowerfactor'] +
        value_json['intervalDatas'][0]['channelIntervalDatas'][2]['averagePowerfactor'] +
        value_json['intervalDatas'][0]['channelIntervalDatas'][3]['averagePowerfactor'] +
        value_json['intervalDatas'][0]['channelIntervalDatas'][4]['averagePowerfactor'] +
        value_json['intervalDatas'][0]['channelIntervalDatas'][5]['averagePowerfactor']) / 6 | round(2)}}"
  unit_of_measurement: '%'
  icon: mdi:gauge
  name: 'Cosinus Ï†'