# mPhone
- platform: mqtt
  state_topic: 'monitor/Keuken/mphone'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'mPhone keuken'
  availability_topic: "monitor/Keuken/status"
  payload_available: "online"
  payload_not_available: "offline"
  json_attributes_topic: 'monitor/Keuken/mphone'

- platform: mqtt
  state_topic: 'monitor/Badkamer/mphone'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'mPhone badkamer'
  availability_topic: "monitor/Badkamer/status"
  payload_available: "online"
  payload_not_available: "offline"
  json_attributes_topic: 'monitor/Badkamer/mphone'

- platform: mqtt
  state_topic: 'monitor/Living/mphone'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'mPhone living'
  availability_topic: "monitor/Living/status"
  payload_available: "online"
  payload_not_available: "offline"
  json_attributes_topic: 'monitor/Living/mphone'

- platform: mqtt
  state_topic: 'monitor/Garage/mphone'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'mPhone garage'
  availability_topic: "monitor/Garage/status"
  payload_available: "online"
  payload_not_available: "offline"
  json_attributes_topic: 'monitor/Garage/mphone'

- platform: mqtt
  state_topic: 'monitor/tvPi/mphone'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'mPhone tvPi'
  availability_topic: "monitor/tvPi/status"
  payload_available: "online"
  payload_not_available: "offline"
  json_attributes_topic: 'monitor/tvPi/mphone'

- platform: mqtt
  state_topic: 'monitor/Pi-Poortje/mphone'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'mPhone PoortPi'
  availability_topic: "monitor/Pi-Poortje/status"
  payload_available: "online"
  payload_not_available: "offline"
  json_attributes_topic: 'monitor/Pi-Poortje/mphone'
  

# VivoSmarti
# - platform: mqtt
#   state_topic: 'monitor/Keuken/C8:3B:BB:14:93:03'
#   value_template: '{{ value_json.confidence }}'
#   unit_of_measurement: '%'
#   name: 'VivoSmart keuken'
#   availability_topic: "monitor/Keuken/status"
#   payload_available: "online"
#   payload_not_available: "offline"
#   json_attributes_topic: 'monitor/Keuken/C8:3B:BB:14:93:03'

# - platform: mqtt
#   state_topic: 'monitor/Living/C8:3B:BB:14:93:03'
#   value_template: '{{ value_json.confidence }}'
#   unit_of_measurement: '%'
#   name: 'VivoSmart living'
#   availability_topic: "monitor/Living/status"
#   payload_available: "online"
#   payload_not_available: "offline"
#   json_attributes:
#   json_attributes_topic: 'monitor/Living/C8:3B:BB:14:93:03'

# - platform: mqtt
#   state_topic: 'monitor/Garage/C8:3B:BB:14:93:03'
#   value_template: '{{ value_json.confidence }}'
#   unit_of_measurement: '%'
#   name: 'VivoSmart garage'
#   availability_topic: "monitor/Garage/status"
#   payload_available: "online"
#   payload_not_available: "offline"
#   json_attributes_topic: 'monitor/Garage/C8:3B:BB:14:93:03'
