  - platform: bayesian
    prior: 0.5
    probability_threshold: 0.9
    name: 'Giel bayesian'
    device_class: presence
    observations:
      # Ping
      - entity_id: 'device_tracker.gphone_ping'
        prob_given_true: 0.89
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'home'
      # IOS app
      - entity_id: 'device_tracker.gphone_2'
        prob_given_true: 0.6
        prob_given_false: 0.4
        platform: 'state'
        to_state: 'home'
      # Bt Monitor
      - entity_id: sensor.gphone_bt_thuis
        prob_given_true: 0.89
        prob_given_false: 0.3
        platform: 'numeric_state'
        above: 43
      # iPhone Detect
      - entity_id: 'device_tracker.gphone_detect'
        prob_given_true: 0.89
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'home'
      # Unifi
      - entity_id: 'device_tracker.gphone'
        prob_given_true: 0.89
        prob_given_false: 0.4
        platform: 'state'
        to_state: 'home'

  - platform: bayesian
    prior: 0.5
    probability_threshold: 0.9
    name: 'Martine bayesian'
    device_class: presence
    observations:
      # Ping
      - entity_id: 'device_tracker.mphone_ping'
        prob_given_true: 0.89
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'home'
      # IOS app
      - entity_id: 'device_tracker.mphone_2'
        prob_given_true: 0.6
        prob_given_false: 0.4
        platform: 'state'
        to_state: 'home'
      # Bt Monitor
      - entity_id: sensor.mphone_bt_thuis
        prob_given_true: 0.89
        prob_given_false: 0.3
        platform: 'numeric_state'
        above: 43
      # iPhone Detect
      - entity_id: 'device_tracker.mphone_detect'
        prob_given_true: 0.89
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'home'
      # Unifi
      - entity_id: 'device_tracker.mphone'
        prob_given_true: 0.89
        prob_given_false: 0.4
        platform: 'state'
        to_state: 'home'
  
  - platform: bayesian
    prior: 0.5
    probability_threshold: 0.9
    name: 'Noor bayesian'
    device_class: presence
    observations:
      # Ping
      - entity_id: 'device_tracker.nphone_ping'
        prob_given_true: 0.89
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'home'
      # # IOS app
      - entity_id: 'device_tracker.nphone'
        prob_given_true: 0.6
        prob_given_false: 0.4
        platform: 'state'
        to_state: 'home'
      # Bt Monitor
      - entity_id: sensor.nphone_bt_thuis
        prob_given_true: 0.89
        prob_given_false: 0.3
        platform: 'numeric_state'
        above: 43
      # iPhone Detect
      - entity_id: 'device_tracker.nphone_detect'
        prob_given_true: 0.89
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'home'
      # Unifi
      - entity_id: 'device_tracker.iphone'
        prob_given_true: 0.89
        prob_given_false: 0.4
        platform: 'state'
        to_state: 'home'
  
  - platform: bayesian
    prior: 0.5
    probability_threshold: 0.9
    name: 'Fien bayesian'
    device_class: presence
    observations:
      # Ping
      - entity_id: 'device_tracker.fphone_ping'
        prob_given_true: 0.89
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'home'
      # # IOS app
      - entity_id: 'device_tracker.fphone'
        prob_given_true: 0.6
        prob_given_false: 0.4
        platform: 'state'
        to_state: 'home'
      # Bt Monitor
      - entity_id: sensor.fphone_bt_thuis
        prob_given_true: 0.89
        prob_given_false: 0.3
        platform: 'numeric_state'
        above: 43
      # iPhone Detect
      - entity_id: 'device_tracker.fphone_detect'
        prob_given_true: 0.89
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'home'
      # Unifi
      - entity_id: 'device_tracker.iphone_2'
        prob_given_true: 0.89
        prob_given_false: 0.4
        platform: 'state'
        to_state: 'home'