  - platform: template
    sensors:
      luster_zithoek_gedrukt:
        friendly_name: Drukknop luster zithoek
        icon_template: mdi:hockey-puck
        entity_id: sensor.shelly_shsw_25_69022d_1_switch
        value_template: "{{ is_state('sensor.shelly_shsw_25_69022d_1_switch', 'on') }}"
      
      luster_danszaal_gedrukt:
        friendly_name: Drukknop luster danszaal
        icon_template: mdi:hockey-puck
        entity_id: sensor.shelly_shsw_25_69022d_2_switch
        value_template: "{{ is_state('sensor.shelly_shsw_25_69022d_2_switch', 'on') }}"
      
      gang_boven_gedrukt:
        friendly_name: Drukknop gang boven
        icon_template: mdi:hockey-puck
        entity_id: sensor.shelly_shsw_25_693e1b_1_switch
        value_template: "{{ is_state('sensor.shelly_shsw_25_693e1b_1_switch', 'on') }}"
      
      slaapkamer_hoog_gedrukt:
        friendly_name: Drukknop slaapkamer hoog
        icon_template: mdi:hockey-puck
        entity_id: sensor.shelly_shsw_25_693e1b_2_switch
        value_template: "{{ is_state('sensor.shelly_shsw_25_693e1b_2_switch', 'on') }}"
      
      inkom_gedrukt:
        friendly_name: Drukknop inkom
        icon_template: mdi:hockey-puck
        entity_id: sensor.shelly_shsw_25_76cbbd_1_switch
        value_template: "{{ is_state('sensor.shelly_shsw_25_76cbbd_1_switch', 'on') }}"
      
      spots_keuken_gedrukt:
        friendly_name: Drukknop spots keuken
        icon_template: mdi:hockey-puck
        entity_id: sensor.shelly_shsw_25_76cbbd_2_switch
        value_template: "{{ is_state('sensor.shelly_shsw_25_76cbbd_2_switch', 'on') }}"
      
      wc_gedrukt:
        friendly_name: Drukknop wc
        icon_template: mdi:hockey-puck
        entity_id: sensor.shelly_shsw_25_76d562_1_switch
        value_template: "{{ is_state('sensor.shelly_shsw_25_76d562_1_switch', 'on') }}"
      
      spotjes_danszaal_gedrukt:
        friendly_name: Drukknop spotjes danszaal
        icon_template: mdi:hockey-puck
        entity_id: sensor.shelly_shsw_25_76d562_2_switch
        value_template: "{{ is_state('sensor.shelly_shsw_25_76d562_2_switch', 'on') }}"
      
      badkamer_hoog_gedrukt:
        friendly_name: Drukknop badkamer hoog
        icon_template: mdi:hockey-puck
        entity_id: sensor.shelly_shsw_25_b939e5_1_switch
        value_template: "{{ is_state('sensor.shelly_shsw_25_b939e5_1_switch', 'on') }}"
      
      badkamer_pombak_gedrukt:
        friendly_name: Drukknop badkamer pombak
        icon_template: mdi:hockey-puck
        entity_id: sensor.shelly_shsw_25_b939e5_2_switch
        value_template: "{{ is_state('sensor.shelly_shsw_25_b939e5_2_switch', 'on') }}"
      
      waskot_gedrukt:
        friendly_name: Drukknop waskot
        icon_template: mdi:hockey-puck
        entity_id: sensor.shelly_shsw_25_b94100_1_switch
        value_template: "{{ is_state('sensor.shelly_shsw_25_b94100_1_switch', 'on') }}"
      
      trap_gedrukt:
        friendly_name: Drukknop trap
        icon_template: mdi:hockey-puck
        entity_id: sensor.shelly_shsw_25_b94100_2_switch
        value_template: "{{ is_state('sensor.shelly_shsw_25_b94100_2_switch', 'on') }}"
      
      luster_keuken_gedrukt:
        friendly_name: Drukknop luster keuken
        icon_template: mdi:hockey-puck
        entity_id: sensor.shelly_shsw_25_b952fa_1_switch
        value_template: "{{ is_state('sensor.shelly_shsw_25_b952fa_1_switch', 'on') }}"
      
      gang_beneden_gedrukt:
        friendly_name: Drukknop gang beneden
        icon_template: mdi:hockey-puck
        entity_id: sensor.shelly_shsw_25_b952fa_2_switch
        value_template: "{{ is_state('sensor.shelly_shsw_25_b952fa_2_switch', 'on') }}"