  alias: Verwarming bij beweging badkamer
  trigger:
    - platform: state
      entity_id: binary_sensor.beweging_badkamer
      to: 'on'
    - platform: state
      entity_id: binary_sensor.beweging_badkamer
      to: 'off'
  action:
    service: climate.set_temperature
    data_template:
      entity_id: climate.badkamer
      temperature: >
        {% if is_state('binary_sensor.beweging_badkamer', 'on') %}
          {{states('input_select.setpunt_badkamer')}}
        {% elif is_state('binary_sensor.beweging_badkamer', 'off') %}
          10
        {% endif %}
