  living_pi3_reboot:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'Living/pi3/system/reboot'
  living_pi3_shut_down:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'Living/pi3/system/shutdown'
          
  living_zero_reboot:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'Living/zero/system/reboot'
  living_zero_shut_down:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'Living/zero/system/shutdown'

  badkamer_reboot:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'Badkamer/system/reboot'
  badkamer_shut_down:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'Badkamer/system/shutdown'

  poortpi_reboot:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'PoortjePi/system/reboot'
  poortpi_shut_down:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'PoortjePi/system/shutdown'

  slaapkamer_reboot:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'Slaapkamer/system/reboot'
  slaapkamer_shut_down:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'Slaapkamer/system/shutdown'

  fien_reboot:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'Fien/system/reboot'
  fien_shut_down:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'Fien/system/shutdown'

  noor_reboot:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'Noor/system/reboot'
  noor_shut_down:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'Noor/system/shutdown'

  keuken_reboot:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'Keuken/system/reboot'
  keuken_shut_down:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'Keuken/system/shutdown'

  verwarmingpi_reboot:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'verwarmingPi/system/reboot'
  verwarmingpi_shut_down:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'verwarmingPi/system/shutdown'

  garage_reboot:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'Garage/system/reboot'
  garage_shut_down:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'Garage/system/shutdown'

  tvpi_reboot:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'tvPi/system/reboot'
  tvpi_shut_down:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'tvPi/system/shutdown'