  verluchting_1_uur:
    sequence:
      - service: switch.turn_on
        entity_id: switch.verluchting
      - delay:
          minutes: 60
      - service: switch.turn_off
        entity_id: switch.verluchting
