  verlichting_hof:
    duration: '00:10:00'
  verlichting_waskot:
    duration: '00:10:00'
  verlichting_wc:
    duration: '00:10:00'
  verlichting_gang_beneden:
    duration: '00:05:00'
  verlichting_gang_boven:
    duration: '00:05:00'
  