sonos_pauze_spreek_nl:
  sequence:
    - condition: and
      conditions:
        - condition: state
          entity_id: media_player.philips_tv
          state: "off"
        # - condition: state
        #   entity_id: binary_sensor.philips_tv_online
        #   state: "off"
        - condition: template
          value_template: "{{states('alarm_control_panel.ha_alarm')  != 'armed_night' }}"
        - condition: or
          conditions:
            - condition: time
              after: "15:55:00"
            - condition: and
              conditions:
                - condition: state
                  entity_id: input_boolean.giel_slaapt_na_nacht
                  state: "off"
                # - condition: state
                #   entity_id: binary_sensor.v_nacht
                #   state: 'off'
    - delay: "00:00:01"
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.keuken
        volume_level: 0.3
    - service: media_player.select_source
      data_template:
        entity_id: media_player.keuken
        source: >
          {{ [
            'Willy',
            'Arrow Classic Rock',
            'New Lords of Metal',
            'Punk Riot',
            'Black Label Extreme Metal Radio',
            'VRT Studio Brussel Bruut',
            'Hard Rock Hell Radio',
            'Brutale Belgen ğŸ‡§ğŸ‡ªğŸ’ªğŸ»â˜ ï¸',
            'MetalRock.FM',
            'VRT Studio Brussel Bruut',
            'Hand of Doom Radio',
            'Real Punk Radio',
            'Het betere genre',
            'Brutale Belgen ğŸ‡§ğŸ‡ªğŸ’ªğŸ»â˜ ï¸',
            'Het betere genre +',
            'Punk In Drublic',
            'VRT Studio Brussel Bruut',
            'Pinguin Aardschok',
            'Pinguin On The Rocks',
            'Belgische gitarenï¿½',
            'GARAGE BANGERS!',
            "PUNK!!! Let's go!!",
            'VAN EIGEN BODEM! (Belgische Gitaren)'
          ] | random }}
