  - platform: darksky
    api_key: !secret dark_sky_api_key
    update_interval:
      minutes: 30
    language: nl
    forecast:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    monitored_conditions:
      - summary
      # - minutely_summary
      - hourly_summary
      - daily_summary
      - cloud_cover
      - precip_type
      - temperature
      - temperature_low
      - temperature_high
      - precip_intensity
      - dew_point
      - wind_speed
      - wind_bearing
      - humidity
