input_boolean:
  spot_slaapkamer_dimmer:
    name: Slaapkamer dimmer
    # initial: off

script:
  dim_spot_slaapkamer:
    sequence:
      - condition: template
        value_template: >
          {{ is_state(('input_boolean.spot_slaapkamer_dimmer'), 'on') }}
      - condition: template
        value_template: "{{  states.light.spot_slaapkamer.attributes.brightness > 11 }}"
      - service: light.turn_on
        data_template:
          entity_id: light.spot_slaapkamer
          brightness: "{{ states.light.spot_slaapkamer.attributes.brightness - 10 }}"
      - service: script.turn_off
        entity_id: script.dim_spot_slaapkamer
      - service: script.dim_spot_slaapkamer

  brighten_spot_slaapkamer:
    sequence:
      - condition: template
        value_template: >
          {{ is_state(('input_boolean.spot_slaapkamer_dimmer'), 'off') }}
      - condition: template
        value_template: "{{  states.light.spot_slaapkamer.attributes.brightness < 246 }}"
      - service: light.turn_on
        data_template:
          entity_id: light.spot_slaapkamer
          brightness: "{{ states.light.spot_slaapkamer.attributes.brightness + 10 }}"
      - service: script.turn_off
        entity_id: script.brighten_spot_slaapkamer
      - service: script.brighten_spot_slaapkamer

automation:     
  - alias: Brighten spot slaapkamer
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.knop_giel_lange_klik
        to: 'on'
      - platform: state
        entity_id: binary_sensor.knop_martine_lange_klik
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: >
            {{ is_state('input_boolean.spot_slaapkamer_dimmer', 'off') }}
        - condition: template
          value_template: >
            {{ is_state('light.spot_slaapkamer', 'on') }}
    action:
      - service: script.brighten_spot_slaapkamer
          
  - alias: Brighten off spot slaapkamer
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.knop_giel_lange_klik
        from: 'on'
        to: 'off'
      - platform: state
        entity_id: binary_sensor.knop_martine_lange_klik
        from: 'on'
        to: 'off'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: >
            {{ is_state('input_boolean.spot_slaapkamer_dimmer', 'off') }}
        - condition: template
          value_template: >
            {{ is_state('light.spot_slaapkamer', 'on') }}
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.spot_slaapkamer_dimmer
          
  - alias: Dim spot slaapkamer
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.knop_giel_lange_klik
        to: 'on'
      - platform: state
        entity_id: binary_sensor.knop_martine_lange_klik
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: >
            {{ is_state('input_boolean.spot_slaapkamer_dimmer', 'on') }}
        - condition: template
          value_template: >
            {{ is_state('light.spot_slaapkamer', 'on') }}
    action:
      - service: script.dim_spot_slaapkamer

  - alias: Dim off spot slaapkamer
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.knop_giel_lange_klik
        from: 'on'
        to: 'off'
      - platform: state
        entity_id: binary_sensor.knop_martine_lange_klik
        from: 'on'
        to: 'off'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: >
            {{ is_state('input_boolean.spot_slaapkamer_dimmer', 'on') }}
        - condition: template
          value_template: >
            {{ is_state('light.spot_slaapkamer', 'on') }}
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.spot_slaapkamer_dimmer
       