  alias: 'Trigger alarm'
  initial_state: 'on' 
  trigger:
    - platform: state
      entity_id: binary_sensor.beweging_hof
      to: 'on'
      for:
        seconds: 15
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.martine_vertrekt_naart_werk
        state: 'off'
      - condition: state
        entity_id: binary_sensor.giel_vertrekt_naart_werk
        state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: alarm_control_panel.ha_alarm
            state: 'armed_away'
          - condition: state
            entity_id: alarm_control_panel.ha_alarm
            state: 'armed_home'
          - condition: state
            entity_id: alarm_control_panel.ha_alarm
            state: 'armed_night'
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.ha_alarm