  alias: Licht hof uit
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.verlichting_hof
  action:
    service: light.turn_off
    entity_id: light.alle_tuinverlichting
