input_boolean:
  allowwhatsapp:
    name: Whatsapp
    icon: mdi:whatsapp

switch:
  - platform: template
    switches:
      allowwhatsapp:
        value_template: "{{ is_state('input_boolean.allowwhatsapp', 'on') }}"
        icon_template: mdi:whatsapp
        friendly_name: Whatsapp
        turn_on:
          - service: input_boolean.turn_on
            data:
              entity_id: input_boolean.allowwhatsapp
        turn_off:
          - service: input_boolean.turn_off
            data:
              entity_id: input_boolean.allowwhatsapp

automation:
  - id: enable_whatsapp
    alias: Enable Whatsapp
    hide_entity: true
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: input_boolean.allowwhatsapp
      to: 'on'
    action:
    - service: adguard.disable_url
      data:
        url: https://raw.githubusercontent.com/gieljnssns/Social-media-Blocklists/master/adguard-whatsapp.txt

  - id: disable_whatsapp
    alias: Disable Whatsapp
    hide_entity: true
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: input_boolean.allowwhatsapp
      to: 'off'
    action:
    - service: adguard.enable_url
      data:
        url: https://raw.githubusercontent.com/gieljnssns/Social-media-Blocklists/master/adguard-whatsapp.txt