  request_gphone_update:
    sequence:
      - service: notify.mobile_app_gphone
        data:
          message: "request_location_update"
  request_mphone_update:
    sequence:
      - service: notify.mobile_app_mphone
        data:
          message: "request_location_update"
  request_nphone_update:
    sequence:
      - service: notify.mobile_app_nphone
        data:
          message: "request_location_update"
  request_fphone_update:
    sequence:
      - service: notify.mobile_app_fphone
        data:
          message: "request_location_update"
  request_all_update:
    sequence:
      - service: notify.ios
        data:
          message: "request_location_update"