mqtt_arrive_depart_script:
  sequence:
  - service: script.mqtt_arrive_trigger
    data_template:
      identity: '{{ identity }}'
  - delay: 00:00:30
  - service: script.mqtt_arrive_trigger
    data_template:
      identity: '{{ identity }}'
  - delay: 00:00:15
  - service: script.mqtt_depart_trigger
    data_template:
      identity: '{{ identity }}'
  - delay: 00:00:15
  - service: script.mqtt_arrive_trigger
    data_template:
      identity: '{{ identity }}'
  - delay: 00:00:30
  - service: script.mqtt_depart_trigger
    data_template:
      identity: '{{ identity }}'
  - delay: 00:00:15
  - service: script.mqtt_arrive_trigger
    data_template:
      identity: '{{ identity }}'
  - delay: 00:00:45
  - service: script.mqtt_depart_trigger
    data_template:
      identity: '{{ identity }}'
  - delay: 00:00:15
  - service: script.mqtt_arrive_trigger
    data_template:
      identity: '{{ identity }}'
  - delay: 00:01:00
  - service: script.mqtt_depart_trigger
    data_template:
      identity: '{{ identity }}'
  - delay: 00:00:15
  - service: script.mqtt_arrive_trigger
    data_template:
      identity: '{{ identity }}'
  - delay: 00:01:15
  - service: script.mqtt_depart_trigger
    data_template:
      identity: '{{ identity }}'
  - delay: 00:00:15
  - service: script.mqtt_arrive_trigger
    data_template:
      identity: '{{ identity }}'
  - delay: 00:01:30
  - service: script.mqtt_depart_trigger
    data_template:
      identity: '{{ identity }}'
  - delay: 00:00:15
  - service: script.mqtt_arrive_trigger
    data_template:
      identity: '{{ identity }}'
  - delay: 00:01:45
  - service: script.mqtt_depart_trigger
    data_template:
      identity: '{{ identity }}'
  - delay: 00:00:15
  - service: script.mqtt_arrive_trigger
    data_template:
      identity: '{{ identity }}'
  - delay: 00:02:00
  - service: script.mqtt_depart_trigger
    data_template:
      identity: '{{ identity }}'
  - delay: 00:00:15
  - service: script.mqtt_arrive_trigger
    data_template:
      identity: '{{ identity }}'