  alias: fPad bluetooth
  trigger:
    - platform: state
      entity_id: sensor.fpad_bt_thuis
  action:
    service_template: >
      {% if states.sensor.fpad_bt_thuis.state | float > 50 %}
         input_boolean.turn_on
      {% else %}
         input_boolean.turn_off
      {% endif %}
    entity_id: input_boolean.fpad_bluetooth
