alias: Martine thuis
trigger:
  - platform: state
    entity_id: input_boolean.martinethuis
    to: 'on'
action:
  service: input_boolean.turn_off
  entity_id:
    - input_boolean.martinebompa
    - input_boolean.martinemoemoe_vava
    - input_boolean.martineoma
    - input_boolean.martinewerk
