exclude:
  domains:
    - weblink
    - updater
    - sun
    - group
  entities:
    - sensor.since_last_boot
    - sensor.date
    - sensor.pws_dewpoint_c
    - sensor.pws_dewpoint_string
    - sensor.pws_feelslike_c
    - sensor.pws_feelslike_string
    - sensor.pws_heat_index_c
    - sensor.pws_heat_index_string
    - sensor.pws_precip_today_metric
    - sensor.pws_precip_today_string
    - sensor.pws_pressure_mb
    - sensor.pws_relative_humidity
    - sensor.pws_solarradiation
    - sensor.pws_station_id
    - sensor.pws_uv
    - sensor.pws_visibility_km
    - sensor.pws_weather
    - sensor.pws_wind_string
    - sensor.ram_use
    - sensor.time
    - sensor.time_date
    - sensor.weer_morgen_condition
    - sensor.weer_morgen_temperature_max
    - sensor.weer_morgen_temperature_min
    - sensor.weer_overmorgen_condition
    - sensor.weer_overmorgen_temperature_max
    - sensor.weer_overmorgen_temperature_min
    - binary_sensor.den_hof_outdoor_animal
    # - binary_sensor.nummer_79_den_hof_outdoor_animal
    - binary_sensor.den_hof_outdoor_motion
    - binary_sensor.den_hof_outdoor_vehicle
    # - binary_sensor.nummer_79_den_hof_outdoor_vehicle
    - climate.netatmo_living_2
    - binary_sensor.binnen_warm
    - binary_sensor.buiten_fris_genoeg
    - binary_sensor.buiten_warm
    - sensor.badkamertemperatuur_mean
    - sensor.beweging_badkamer_count
    - sensor.beweging_slaapkamer_count
    - sensor.beweging_slaapkamer_fien_count
    - sensor.beweging_slaapkamer_noor_count
    - sensor.buienradar
    - sensor.bureau
    - sensor.fien
    - sensor.noor
    - sensor.opladers
    - sensor.slaapkamer
    - sensor.temperatuur_living_mean
    - sensor.verluchting
    - sensor.wc
    - zone.home
