port: 51827
# ip_address: !secret apple_tv_host
filter:
  include_entities:
    - input_boolean.presence_licht_aan
    - input_boolean.koogeek_achterdeur
    - input_boolean.koogeek_voordeur
    - light.alle_tuinverlichting
    - light.den_hof
    - light.terras
    - light.fien
    - light.noor
    - light.spots_tv
    - switch.shelly_shplg_s_7ae974
    - switch.badkamer
    - switch.slaapkamer
    - switch.noor
    - switch.fien
entity_config:
  light.alle_tuinverlichting:
    name: Verlichting buiten
  light.den_hof:
    name: Tuinverlichting
  light.terras:
    name: Terrasverlichting
  light.fien:
    name: Licht slaapkamer Fien
  light.noor:
    name: Licht slaapkamer Noor
  light.spots_tv:
    name: Licht zithoek
  switch.shelly_shplg_s_7ae974:
    name: Koffiezet
    type: outlet
  switch.badkamer:
    name: Verwarming badkamer
    type: outlet
  switch.slaapkamer:
    name: Verwarming slaapkamer
    type: outlet
  switch.noor:
    name: Verwarming slaapkamer Noor
    type: outlet
  switch.fien:
    name: Verwarming slaapkamer Fien
    type: outlet
