  base_url: !secret base_url
  ip_ban_enabled: True
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    # - 192.168.79.54
    # - 192.168.79.0/24
    # - 172.30.33.0/24
    - ::1
  login_attempts_threshold: 5