Playlists: # http://192.168.79.54:8123/lib/mass/#/playlists
  70s Rock Anthems: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/17
    media_content_id: media-source://mass/database://playlist/17
    media_content_type: playlist
    enqueue: replace
  80s Rock Anthems: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/15
    media_content_id: media-source://mass/database://playlist/15
    media_content_type: playlist
    enqueue: replace
  Addergebroed jaarlijst 2021 - Cas: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/1
    media_content_id: media-source://mass/database://playlist/1
    media_content_type: playlist
    enqueue: replace
  Addergebroed jaarlijst 2021 - Jokke: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/3
    media_content_id: media-source://mass/database://playlist/3
    media_content_type: playlist
    enqueue: replace
  Addergebroed jaarlijst 2021 - Jules: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/2
    media_content_id: media-source://mass/database://playlist/2
    media_content_type: playlist
    enqueue: replace
  De allerzwaarste lijst: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/10
    media_content_id: media-source://mass/database://playlist/10
    media_content_type: playlist
    enqueue: replace
  BELGIAN UNDERGROUND: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/6
    media_content_id: media-source://mass/database://playlist/6
    media_content_type: playlist
    enqueue: replace
  Belgische gitarenğŸ¤˜: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/5
    media_content_id: media-source://mass/database://playlist/5
    media_content_type: playlist
    enqueue: replace
  Best of NAPALM RECORDS: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/41
    media_content_id: media-source://mass/database://playlist/41
    media_content_type: playlist
    enqueue: replace
  Bonzai Records: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/21
    media_content_id: media-source://mass/database://playlist/21
    media_content_type: playlist
    enqueue: replace
  Brutaliteit uit de lage landenğŸ‡§ğŸ‡ªâ˜ ï¸ğŸ‡³ğŸ‡±: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/8
    media_content_id: media-source://mass/database://playlist/8
    media_content_type: playlist
    enqueue: replace
  Cherrymoon, Bonzai Records, Zillion, Atmoz, mix mania: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/22
    media_content_id: media-source://mass/database://playlist/22
    media_content_type: playlist
    enqueue: replace
  De complete kleinkunst collectie: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/28
    media_content_id: media-source://mass/database://playlist/28
    media_content_type: playlist
    enqueue: replace
  Crash Course: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/36
    media_content_id: media-source://mass/database://playlist/36
    media_content_type: playlist
    enqueue: replace
  Damned Soul Fest IV: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/47
    media_content_id: media-source://mass/database://playlist/47
    media_content_type: playlist
    enqueue: replace
  Dessertfest 2022: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/45
    media_content_id: media-source://mass/database://playlist/45
    media_content_type: playlist
    enqueue: replace
  Dessertfest 2022_2: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/46
    media_content_id: media-source://mass/database://playlist/46
    media_content_type: playlist
    enqueue: replace
  Discover Weekly: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/40
    media_content_id: media-source://mass/database://playlist/40
    media_content_type: playlist
    enqueue: replace
  Doom / Stoner / Sludge: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/25
    media_content_id: media-source://mass/database://playlist/25
    media_content_type: playlist
    enqueue: replace
  Doom | Sludge | Black Metal | Post-Metal | Stoner | Death Metal: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/26
    media_content_id: media-source://mass/database://playlist/26
    media_content_type: playlist
    enqueue: replace
  Doom/Stoner/Sludge Metal: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/34
    media_content_id: media-source://mass/database://playlist/34
    media_content_type: playlist
    enqueue: replace
  Dunk!Festival: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/35
    media_content_id: media-source://mass/database://playlist/35
    media_content_type: playlist
    enqueue: replace
  Extreme Metal Workout: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/39
    media_content_id: media-source://mass/database://playlist/39
    media_content_type: playlist
    enqueue: replace
  Garage Punk Rock and Roll: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/7
    media_content_id: media-source://mass/database://playlist/7
    media_content_type: playlist
    enqueue: replace
  Gitannekesfoor: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/33
    media_content_id: media-source://mass/database://playlist/33
    media_content_type: playlist
    enqueue: replace
  Gitannekesfoor Radio: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/37
    media_content_id: media-source://mass/database://playlist/37
    media_content_type: playlist
    enqueue: replace
  The Greatest Switch â€” StuBru: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/19
    media_content_id: media-source://mass/database://playlist/19
    media_content_type: playlist
    enqueue: replace
  Kleine Kunst: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/9
    media_content_id: media-source://mass/database://playlist/9
    media_content_type: playlist
    enqueue: replace
  Noor - Fien: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/23
    media_content_id: media-source://mass/database://playlist/23
    media_content_type: playlist
    enqueue: replace
  Punk In Drublic: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/11
    media_content_id: media-source://mass/database://playlist/11
    media_content_type: playlist
    enqueue: replace
  PUNK!!! Let's go!!: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/4
    media_content_id: media-source://mass/database://playlist/4
    media_content_type: playlist
    enqueue: replace
  Radio-favorieten: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/43
    media_content_id: media-source://mass/database://playlist/43
    media_content_type: playlist
    enqueue: replace
  Release Radar: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/38
    media_content_id: media-source://mass/database://playlist/38
    media_content_type: playlist
    enqueue: replace
  Retro House Classics Dance Trance: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/20
    media_content_id: media-source://mass/database://playlist/20
    media_content_type: playlist
    enqueue: replace
  Rock Classics: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/14
    media_content_id: media-source://mass/database://playlist/14
    media_content_type: playlist
    enqueue: replace
  Shoegaze Classics: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/42
    media_content_id: media-source://mass/database://playlist/42
    media_content_type: playlist
    enqueue: replace
  Sjock 44: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/29
    media_content_id: media-source://mass/database://playlist/29
    media_content_type: playlist
    enqueue: replace
  This Is Amenra: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/44
    media_content_id: media-source://mass/database://playlist/44
    media_content_type: playlist
    enqueue: replace
  This is Belgium: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/30
    media_content_id: media-source://mass/database://playlist/30
    media_content_type: playlist
    enqueue: replace
  Voodoo Rhythm Records: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/27
    media_content_id: media-source://mass/database://playlist/27
    media_content_type: playlist
    enqueue: replace
  Your Top Songs 2018: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/32
    media_content_id: media-source://mass/database://playlist/32
    media_content_type: playlist
    enqueue: replace
  De Zwaarste Lijst â€” StuBru: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/18
    media_content_id: media-source://mass/database://playlist/18
    media_content_type: playlist
    enqueue: replace
  Zware Metalen Jaarlijst | 2017: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/31
    media_content_id: media-source://mass/database://playlist/31
    media_content_type: playlist
    enqueue: replace
  Zware Metalen Jaarlijst | 2018: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/13
    media_content_id: media-source://mass/database://playlist/13
    media_content_type: playlist
    enqueue: replace
  80s Hard Rock: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/16
    media_content_id: media-source://mass/database://playlist/16
    media_content_type: playlist
    enqueue: replace
  ğŸ†Rauwe KostğŸ‘: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/24
    media_content_id: media-source://mass/database://playlist/24
    media_content_type: playlist
    enqueue: replace
  ğŸ’€ğŸ¤˜ğŸ»Zware ğŸ‡§ğŸ‡ªğŸ‡§ğŸ‡ªğŸ‡§ğŸ‡ª metalen ğŸ¤˜ğŸ»ğŸ’€: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/12
    media_content_id: media-source://mass/database://playlist/12
    media_content_type: playlist
    enqueue: replace
  Sjock 45: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/48
    media_content_id: media-source://mass/database://playlist/48
    media_content_type: playlist
    enqueue: replace
  # : 
  #   url: http://192.168.79.54:8123/lib/mass/#/playlists/database/
  #   media_content_id: media-source://mass/database://playlist/
  #   media_content_type: playlist
  #   enqueue: replace
  # : 
  #   url: http://192.168.79.54:8123/lib/mass/#/playlists/database/
  #   media_content_id: media-source://mass/database://playlist/
  #   media_content_type: playlist
  #   enqueue: replace
  # : 
  #   url: http://192.168.79.54:8123/lib/mass/#/playlists/database/
  #   media_content_id: media-source://mass/database://playlist/
  #   media_content_type: playlist
  #   enqueue: replace
  # : 
  #   url: http://192.168.79.54:8123/lib/mass/#/playlists/database/
  #   media_content_id: media-source://mass/database://playlist/
  #   media_content_type: playlist
  #   enqueue: replace
  # : 
  #   url: http://192.168.79.54:8123/lib/mass/#/playlists/database/
  #   media_content_id: media-source://mass/database://playlist/
  #   media_content_type: playlist
  #   enqueue: replace
  # : 
  #   url: http://192.168.79.54:8123/lib/mass/#/playlists/database/
  #   media_content_id: media-source://mass/database://playlist/
  #   media_content_type: playlist
  #   enqueue: replace
  # : 
  #   url: http://192.168.79.54:8123/lib/mass/#/playlists/database/
  #   media_content_id: media-source://mass/database://playlist/
  #   media_content_type: playlist
  #   enqueue: replace
  # : 
  #   url: http://192.168.79.54:8123/lib/mass/#/playlists/database/
  #   media_content_id: media-source://mass/database://playlist/
  #   media_content_type: playlist
  #   enqueue: replace
  # : 
  #   url: http://192.168.79.54:8123/lib/mass/#/playlists/database/
  #   media_content_id: media-source://mass/database://playlist/
  #   media_content_type: playlist
  #   enqueue: replace
  # : 
  #   url: http://192.168.79.54:8123/lib/mass/#/playlists/database/
  #   media_content_id: media-source://mass/database://playlist/
  #   media_content_type: playlist
  #   enqueue: replace
  # : 
  #   url: http://192.168.79.54:8123/lib/mass/#/playlists/database/
  #   media_content_id: media-source://mass/database://playlist/
  #   media_content_type: playlist
  #   enqueue: replace

Radio: # http://192.168.79.54:8123/lib/mass/#/radios
  Arrow Classic Rock:
    media_content_id: media-source://mass/database://radio/6
    media_content_type: audio/flac
  VRT Studio Brussel Bruut:
    media_content_id: media-source://mass/database://radio/1
    media_content_type: audio/flac
  Studio Brussel:
    media_content_id: media-source://mass/database://radio/2
    media_content_type: audio/flac
  Pinguin on the rocks:
    media_content_id: media-source://mass/database://radio/4
    media_content_type: audio/flac
  MetalrockFM:
    media_content_id: media-source://mass/database://radio/5
    media_content_type: audio/flac
  Hand of doom radio:
    media_content_id: media-source://mass/database://radio/7
    media_content_type: audio/flac
  Real punk radio:
    media_content_id: media-source://mass/database://radio/8
    media_content_type: audio/flac
  Hard rock hell radio:
    media_content_id: media-source://mass/database://radio/9
    media_content_type: audio/flac
  Pinguin aardschok:
    media_content_id: media-source://mass/database://radio/3
    media_content_type: audio/flac
  Riot FM:
    media_content_id: media-source://mass/database://radio/10
    media_content_type: audio/flac
  Willy:
    media_content_id: media-source://mass/database://radio/11
    media_content_type: audio/flac



































