Playlists: # http://192.168.79.54:8123/lib/mass/#/playlists
  70s Rock Anthems: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/17
    media_content_id: media-source://mass/database://playlist/17
    media_content_type: playlist
    enqueue: replace
  80s Rock Anthems: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/15
    media_content_id: media-source://mass/database://playlist/15
    media_content_type: playlist
    enqueue: replace
  Addergebroed jaarlijst 2021 - Cas: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/1
    media_content_id: media-source://mass/database://playlist/1
    media_content_type: playlist
    enqueue: replace
  Addergebroed jaarlijst 2021 - Jokke: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/3
    media_content_id: media-source://mass/database://playlist/3
    media_content_type: playlist
    enqueue: replace
  Addergebroed jaarlijst 2021 - Jules: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/2
    media_content_id: media-source://mass/database://playlist/2
    media_content_type: playlist
    enqueue: replace
  De allerzwaarste lijst: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/10
    media_content_id: media-source://mass/database://playlist/10
    media_content_type: playlist
    enqueue: replace
  BELGIAN UNDERGROUND: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/6
    media_content_id: media-source://mass/database://playlist/6
    media_content_type: playlist
    enqueue: replace
  Belgische gitarenğŸ¤˜: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/5
    media_content_id: media-source://mass/database://playlist/5
    media_content_type: playlist
    enqueue: replace
  Best of NAPALM RECORDS: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/41
    media_content_id: media-source://mass/database://playlist/41
    media_content_type: playlist
    enqueue: replace
  Bonzai Records: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/21
    media_content_id: media-source://mass/database://playlist/21
    media_content_type: playlist
    enqueue: replace
  Brutaliteit uit de lage landenğŸ‡§ğŸ‡ªâ˜ ï¸ğŸ‡³ğŸ‡±: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/8
    media_content_id: media-source://mass/database://playlist/8
    media_content_type: playlist
    enqueue: replace
  Cherrymoon, Bonzai Records, Zillion, Atmoz, mix mania: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/22
    media_content_id: media-source://mass/database://playlist/22
    media_content_type: playlist
    enqueue: replace
  De complete kleinkunst collectie: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/28
    media_content_id: media-source://mass/database://playlist/28
    media_content_type: playlist
    enqueue: replace
  Crash Course: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/36
    media_content_id: media-source://mass/database://playlist/36
    media_content_type: playlist
    enqueue: replace
  Damned Soul Fest IV: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/47
    media_content_id: media-source://mass/database://playlist/47
    media_content_type: playlist
    enqueue: replace
  Dessertfest 2022: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/45
    media_content_id: media-source://mass/database://playlist/45
    media_content_type: playlist
    enqueue: replace
  Dessertfest 2022_2: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/46
    media_content_id: media-source://mass/database://playlist/46
    media_content_type: playlist
    enqueue: replace
  Discover Weekly: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/40
    media_content_id: media-source://mass/database://playlist/40
    media_content_type: playlist
    enqueue: replace
  Doom / Stoner / Sludge: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/25
    media_content_id: media-source://mass/database://playlist/25
    media_content_type: playlist
    enqueue: replace
  Doom | Sludge | Black Metal | Post-Metal | Stoner | Death Metal: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/26
    media_content_id: media-source://mass/database://playlist/26
    media_content_type: playlist
    enqueue: replace
  Doom/Stoner/Sludge Metal: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/34
    media_content_id: media-source://mass/database://playlist/34
    media_content_type: playlist
    enqueue: replace
  Dunk!Festival: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/35
    media_content_id: media-source://mass/database://playlist/35
    media_content_type: playlist
    enqueue: replace
  Extreme Metal Workout: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/39
    media_content_id: media-source://mass/database://playlist/39
    media_content_type: playlist
    enqueue: replace
  Garage Punk Rock and Roll: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/7
    media_content_id: media-source://mass/database://playlist/7
    media_content_type: playlist
    enqueue: replace
  Gitannekesfoor: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/33
    media_content_id: media-source://mass/database://playlist/33
    media_content_type: playlist
    enqueue: replace
  Gitannekesfoor Radio: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/37
    media_content_id: media-source://mass/database://playlist/37
    media_content_type: playlist
    enqueue: replace
  The Greatest Switch â€” StuBru: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/19
    media_content_id: media-source://mass/database://playlist/19
    media_content_type: playlist
    enqueue: replace
  Kleine Kunst: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/9
    media_content_id: media-source://mass/database://playlist/9
    media_content_type: playlist
    enqueue: replace
  Noor - Fien: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/23
    media_content_id: media-source://mass/database://playlist/23
    media_content_type: playlist
    enqueue: replace
  Punk In Drublic: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/11
    media_content_id: media-source://mass/database://playlist/11
    media_content_type: playlist
    enqueue: replace
  PUNK!!! Let's go!!: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/4
    media_content_id: media-source://mass/database://playlist/4
    media_content_type: playlist
    enqueue: replace
  Radio-favorieten: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/43
    media_content_id: media-source://mass/database://playlist/43
    media_content_type: playlist
    enqueue: replace
  Release Radar: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/38
    media_content_id: media-source://mass/database://playlist/38
    media_content_type: playlist
    enqueue: replace
  Retro House Classics Dance Trance: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/20
    media_content_id: media-source://mass/database://playlist/20
    media_content_type: playlist
    enqueue: replace
  Rock Classics: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/14
    media_content_id: media-source://mass/database://playlist/14
    media_content_type: playlist
    enqueue: replace
  Shoegaze Classics: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/42
    media_content_id: media-source://mass/database://playlist/42
    media_content_type: playlist
    enqueue: replace
  Sjock 44: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/29
    media_content_id: media-source://mass/database://playlist/29
    media_content_type: playlist
    enqueue: replace
  This Is Amenra: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/44
    media_content_id: media-source://mass/database://playlist/44
    media_content_type: playlist
    enqueue: replace
  This is Belgium: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/30
    media_content_id: media-source://mass/database://playlist/30
    media_content_type: playlist
    enqueue: replace
  Voodoo Rhythm Records: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/27
    media_content_id: media-source://mass/database://playlist/27
    media_content_type: playlist
    enqueue: replace
  Your Top Songs 2018: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/32
    media_content_id: media-source://mass/database://playlist/32
    media_content_type: playlist
    enqueue: replace
  De Zwaarste Lijst â€” StuBru: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/18
    media_content_id: media-source://mass/database://playlist/18
    media_content_type: playlist
    enqueue: replace
  Zware Metalen Jaarlijst | 2017: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/31
    media_content_id: media-source://mass/database://playlist/31
    media_content_type: playlist
    enqueue: replace
  Zware Metalen Jaarlijst | 2018: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/13
    media_content_id: media-source://mass/database://playlist/13
    media_content_type: playlist
    enqueue: replace
  80s Hard Rock: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/16
    media_content_id: media-source://mass/database://playlist/16
    media_content_type: playlist
    enqueue: replace
  ğŸ†Rauwe KostğŸ‘: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/24
    media_content_id: media-source://mass/database://playlist/24
    media_content_type: playlist
    enqueue: replace
  ğŸ’€ğŸ¤˜ğŸ»Zware ğŸ‡§ğŸ‡ªğŸ‡§ğŸ‡ªğŸ‡§ğŸ‡ª metalen ğŸ¤˜ğŸ»ğŸ’€: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/12
    media_content_id: media-source://mass/database://playlist/12
    media_content_type: playlist
    enqueue: replace
  Sjock 45: 
    url: http://192.168.79.54:8123/lib/mass/#/playlists/database/48
    media_content_id: media-source://mass/database://playlist/48
    media_content_type: playlist
    enqueue: replace
  # : 
  #   url: http://192.168.79.54:8123/lib/mass/#/playlists/database/
  #   media_content_id: media-source://mass/database://playlist/
  #   media_content_type: playlist
  #   enqueue: replace
  # : 
  #   url: http://192.168.79.54:8123/lib/mass/#/playlists/database/
  #   media_content_id: media-source://mass/database://playlist/
  #   media_content_type: playlist
  #   enqueue: replace
  # : 
  #   url: http://192.168.79.54:8123/lib/mass/#/playlists/database/
  #   media_content_id: media-source://mass/database://playlist/
  #   media_content_type: playlist
  #   enqueue: replace
  # : 
  #   url: http://192.168.79.54:8123/lib/mass/#/playlists/database/
  #   media_content_id: media-source://mass/database://playlist/
  #   media_content_type: playlist
  #   enqueue: replace
  # : 
  #   url: http://192.168.79.54:8123/lib/mass/#/playlists/database/
  #   media_content_id: media-source://mass/database://playlist/
  #   media_content_type: playlist
  #   enqueue: replace
  # : 
  #   url: http://192.168.79.54:8123/lib/mass/#/playlists/database/
  #   media_content_id: media-source://mass/database://playlist/
  #   media_content_type: playlist
  #   enqueue: replace
  # : 
  #   url: http://192.168.79.54:8123/lib/mass/#/playlists/database/
  #   media_content_id: media-source://mass/database://playlist/
  #   media_content_type: playlist
  #   enqueue: replace
  # : 
  #   url: http://192.168.79.54:8123/lib/mass/#/playlists/database/
  #   media_content_id: media-source://mass/database://playlist/
  #   media_content_type: playlist
  #   enqueue: replace
  # : 
  #   url: http://192.168.79.54:8123/lib/mass/#/playlists/database/
  #   media_content_id: media-source://mass/database://playlist/
  #   media_content_type: playlist
  #   enqueue: replace
  # : 
  #   url: http://192.168.79.54:8123/lib/mass/#/playlists/database/
  #   media_content_id: media-source://mass/database://playlist/
  #   media_content_type: playlist
  #   enqueue: replace
  # : 
  #   url: http://192.168.79.54:8123/lib/mass/#/playlists/database/
  #   media_content_id: media-source://mass/database://playlist/
  #   media_content_type: playlist
  #   enqueue: replace

Radio: # http://192.168.79.54:8123/lib/mass/#/radios
  Arrow Classic Rock:
    media_content_id: media-source://mass/database://radio/6
    media_content_type: audio/flac
  VRT Studio Brussel Bruut:
    media_content_id: media-source://mass/database://radio/1
    media_content_type: audio/flac
  Studio Brussel:
    media_content_id: media-source://mass/database://radio/2
    media_content_type: audio/flac
  Pinguin on the rocks:
    media_content_id: media-source://mass/database://radio/4
    media_content_type: audio/flac
  MetalrockFM:
    media_content_id: media-source://mass/database://radio/5
    media_content_type: audio/flac
  Hand of doom radio:
    media_content_id: media-source://mass/database://radio/7
    media_content_type: audio/flac
  Real punk radio:
    media_content_id: media-source://mass/database://radio/8
    media_content_type: audio/flac
  Hard rock hell radio:
    media_content_id: media-source://mass/database://radio/9
    media_content_type: audio/flac
  Pinguin aardschok:
    media_content_id: media-source://mass/database://radio/3
    media_content_type: audio/flac
  Riot FM:
    media_content_id: media-source://mass/database://radio/10
    media_content_type: audio/flac
  Willy:
    media_content_id: media-source://mass/database://radio/11
    media_content_type: audio/flac



0
: 
{item_id: '98', name: ''}
1
: 
{item_id: '22', name: '0A'}
2
: 
{item_id: '72', name: '10 beste black albums'}
3
: 
{item_id: '21', name: '2022 - A Playlist Curated By The Evil Greed Staff'}
4
: 
{item_id: '47', name: '45 years of Sjock Festival Gierle - Belgium'}
5
: 
{item_id: '50', name: 'Addergebroed jaarlijst 2021 - Cas'}
6
: 
{item_id: '51', name: 'Addergebroed jaarlijst 2021 - Jokke'}
7
: 
{item_id: '49', name: 'Addergebroed jaarlijst 2021 - Jules'}
8
: 
{item_id: '61', name: 'Alcatraz 2021 ALL'}
9
: 
{item_id: '73', name: 'Alternative Metal'}
10
: 
{item_id: '13', name: "BARST - MOSH THE 90'S"}
11
: 
{item_id: '14', name: 'BARST - SUPPORT YOUR LOCALS'}
12
: 
{item_id: '12', name: 'Barst 2022'}
13
: 
{item_id: '57', name: 'BELGIAN UNDERGROUND'}
14
: 
{item_id: '74', name: 'Best Black Metal on Spotify'}
15
: 
{item_id: '20', name: 'Best of 2022 (WPRD)'}
16
: 
{item_id: '28', name: 'Best of Deathwish'}
17
: 
{item_id: '92', name: 'Best of NAPALM RECORDS'}
18
: 
{item_id: '16', name: 'Binnenkort @ De Bosuil'}
19
: 
{item_id: '80', name: 'Black metal'}
20
: 
{item_id: '60', name: 'Black Metal Media'}
21
: 
{item_id: '63', name: 'Black/Death/Trash Metal'}
22
: 
{item_id: '99', name: 'Bonzai Records'}
23
: 
{item_id: '17', name: 'Brutaliteit uit de lage landenğŸ‡§ğŸ‡ªâ˜ ï¸ğŸ‡³ğŸ‡±' }
24
: 
{item_id: '55', name: 'BRUUT'}
25
: 
{item_id: '54', name: 'Bruut â€” StuBru'}
26
: 
{item_id: '104', name: 'Carat'}
27
: 
{item_id: '102', name: 'Cherrymoon, Bonzai Records, Zillion, Atmoz, mix mania'}
28
: 
{item_id: '90', name: 'Classic Road Trip Songs'}
29
: 
{item_id: '65', name: "Coding / Hacking / Feeling like a 80's scifi superhero"}
30
: 
{item_id: '86', name: 'De complete kleinkunst collectie'}
31
: 
{item_id: '95', name: 'Crash Course'}
32
: 
{item_id: '40', name: 'Crunchy Riffs To Get You High'}
33
: 
{item_id: '27', name: 'Damned Soul Fest IV'}
34
: 
{item_id: '38', name: 'Death Metal Destroyers'}
35
: 
{item_id: '29', name: 'Dessertfest 2022'}
36
: 
{item_id: '64', name: 'Doodseskader Radio'}
37
: 
{item_id: '85', name: 'Doom / Stoner / Sludge'}
38
: 
{item_id: '101', name: 'Doom/Stoner/Sludge Metal'}
39
: 
{item_id: '41', name: 'Dutch Black Metal'}
40
: 
{item_id: '26', name: 'DÃ¶dsrit Radio'}
41
: 
{item_id: '43', name: 'Every Stranger Looks Like You: Ğ¼Ğ¸ĞºÑ'}
42
: 
{item_id: '94', name: 'Extreme Metal Workout'}
43
: 
{item_id: '75', name: 'Fur Martine'}
44
: 
{item_id: '58', name: 'Garage, Punk & Psych'}
45
: 
{item_id: '7', name: 'Hand-Picked & Heavy'}
46
: 
{item_id: '15', name: 'Headbangers Parade #1'}
47
: 
{item_id: '34', name: 'Ieperfest'}
48
: 
{item_id: '35', name: 'Ieperfest 2022'}
49
: 
{item_id: '77', name: 'Kleine Kunst'}
50
: 
{item_id: '81', name: 'LEVITATION 2019 - Official Playlist'}
51
: 
{item_id: '66', name: 'LEVITATION 2021 : Official Playlist'}
52
: 
{item_id: '44', name: 'LEVITATION : HEAVY ROTATION'}
53
: 
{item_id: '8', name: "Metal Injection's Top Tracks Of The Week"}
54
: 
{item_id: '52', name: 'Metalfan.nl Klassiekers Van De Dag'}
55
: 
{item_id: '1', name: 'MOSH INC.'}
56
: 
{item_id: '88', name: 'New Noise'}
57
: 
{item_id: '24', name: 'NMTH Bruut Nationaal Product'}
58
: 
{item_id: '25', name: 'NMTH Hardhitters'}
59
: 
{item_id: '103', name: 'Nog te luisteren'}
60
: 
{item_id: '84', name: 'Noor - Fien'}
61
: 
{item_id: '37', name: 'Paint It, Black'}
62
: 
{item_id: '105', name: 'POWERMIXES'}
63
: 
{item_id: '3', name: 'Pulse Of The Maggots (Knotfest)'}
64
: 
{item_id: '78', name: 'Punk In Drublic'}
65
: 
{item_id: '42', name: 'RAFC Sound of Bosuil'}
66
: 
{item_id: '76', name: 'Rauwe Kost'}
67
: 
{item_id: '67', name: 'Relapse Records Doom / Sludge / Stoner Metal Mix'}
68
: 
{item_id: '68', name: 'Relapse Records Most Played Tracks'}
69
: 
{item_id: '70', name: 'Relapse Records New & Notable'}
70
: 
{item_id: '69', name: 'Relapse Records Staff Picks'}
71
: 
{item_id: '71', name: 'Release Radar'}
72
: 
{item_id: '59', name: 'Retro House Music (Belgium)'}
73
: 
{item_id: '62', name: 'Rise And Fall Roadtrip'}
74
: 
{item_id: '4', name: 'Roadburn: Essential Sounds'}
75
: 
{item_id: '96', name: 'Rock Classics'}
76
: 
{item_id: '32', name: 'RONKERS RAUWKOST'}
77
: 
{item_id: '83', name: 'Ruig & Riffs'}
78
: 
{item_id: '106', name: 'Run Forrest Run!'}
79
: 
{item_id: '31', name: 'Samhain - Office playlist'}
80
: 
{item_id: '48', name: 'SJOCK Festival 45'}
81
: 
{item_id: '30', name: 'Soulcrusher 2022'}
82
: 
{item_id: '46', name: 'Stoner'}
83
: 
{item_id: '36', name: 'This is Belgium not the USA'}
84
: 
{item_id: '87', name: 'This is: Belgium'}
85
: 
{item_id: '19', name: 'TIZIZIT: Bonecrusher ğŸ’€'}
86
: 
{item_id: '79', name: 'Trash metal'}
87
: 
{item_id: '2', name: 'Ultimate Sludge Metal'}
88
: 
{item_id: '39', name: "The Underground Metal Bands You Might've Missed"}
89
: 
{item_id: '9', name: 'Vicious Volumes'}
90
: 
{item_id: '10', name: 'Vocal Distortion: Riffs On Repeat'}
91
: 
{item_id: '91', name: 'Voodoo Rhythm Records'}
92
: 
{item_id: '93', name: 'Voodoo Rhythm Records & Co.'}
93
: 
{item_id: '18', name: 'Wachtrij'}
94
: 
{item_id: '45', name: 'Weedian (Worldwide)'}
95
: 
{item_id: '53', name: 'Weedian - Trip to The Netherlands'}
96
: 
{item_id: '11', name: 'YOUR DAILY METAL | best new metal & core tracks'}
97
: 
{item_id: '56', name: 'Your Top Songs 2021'}
98
: 
{item_id: '23', name: 'Your Top Songs 2022'}
99
: 
{item_id: '97', name: 'De Zwaarste Lijst  â€” StuBru', provi






# nog aan te passen
# tts.speak























