purge_keep_days: 7
db_url: !secret mysql
exclude:
  domains:
    - camera
    - group
    - history_graph
    - scene
    - sun
    - timer
    - weather
    - zone
  entities:
    - binary_sensor.bluetooth_scan
    - binary_sensor.iss
    - sensor.dark_sky_cloud_coverage_1
    - sensor.dark_sky_cloud_coverage_2
    - sensor.dark_sky_cloud_coverage_3
    - sensor.dark_sky_cloud_coverage_4
    - sensor.dark_sky_cloud_coverage_5
    - sensor.dark_sky_cloud_coverage_6
    - sensor.dark_sky_cloud_coverage_7
    - sensor.dark_sky_daily_summary
    - sensor.dark_sky_daytime_high_temperature
    - sensor.dark_sky_daytime_high_temperature_1
    - sensor.dark_sky_daytime_high_temperature_2
    - sensor.dark_sky_daytime_high_temperature_3
    - sensor.dark_sky_daytime_high_temperature_4
    - sensor.dark_sky_daytime_high_temperature_5
    - sensor.dark_sky_daytime_high_temperature_6
    - sensor.dark_sky_daytime_high_temperature_7
    - sensor.dark_sky_dew_point_1
    - sensor.dark_sky_dew_point_2
    - sensor.dark_sky_dew_point_3
    - sensor.dark_sky_dew_point_4
    - sensor.dark_sky_dew_point_5
    - sensor.dark_sky_dew_point_6
    - sensor.dark_sky_dew_point_7
    - sensor.dark_sky_hourly_summary
    - sensor.dark_sky_humidity_1
    - sensor.dark_sky_humidity_2
    - sensor.dark_sky_humidity_3
    - sensor.dark_sky_humidity_4
    - sensor.dark_sky_humidity_5
    - sensor.dark_sky_humidity_6
    - sensor.dark_sky_humidity_7
    - sensor.dark_sky_overnight_low_temperature
    - sensor.dark_sky_overnight_low_temperature_1
    - sensor.dark_sky_overnight_low_temperature_2
    - sensor.dark_sky_overnight_low_temperature_3
    - sensor.dark_sky_overnight_low_temperature_4
    - sensor.dark_sky_overnight_low_temperature_5
    - sensor.dark_sky_overnight_low_temperature_6
    - sensor.dark_sky_overnight_low_temperature_7
    - sensor.dark_sky_precip_1
    - sensor.dark_sky_precip_2
    - sensor.dark_sky_precip_3
    - sensor.dark_sky_precip_4
    - sensor.dark_sky_precip_5
    - sensor.dark_sky_precip_6
    - sensor.dark_sky_precip_7
    - sensor.dark_sky_precip_intensity_1
    - sensor.dark_sky_precip_intensity_2
    - sensor.dark_sky_precip_intensity_3
    - sensor.dark_sky_precip_intensity_4
    - sensor.dark_sky_precip_intensity_5
    - sensor.dark_sky_precip_intensity_6
    - sensor.dark_sky_precip_intensity_7
    - sensor.dark_sky_summary
    - sensor.dark_sky_wind_bearing_1
    - sensor.dark_sky_wind_bearing_2
    - sensor.dark_sky_wind_bearing_3
    - sensor.dark_sky_wind_bearing_4
    - sensor.dark_sky_wind_bearing_5
    - sensor.dark_sky_wind_bearing_6
    - sensor.dark_sky_wind_bearing_7
    - sensor.dark_sky_wind_speed_1
    - sensor.dark_sky_wind_speed_2
    - sensor.dark_sky_wind_speed_3
    - sensor.dark_sky_wind_speed_4
    - sensor.dark_sky_wind_speed_5
    - sensor.dark_sky_wind_speed_6
    - sensor.dark_sky_wind_speed_7
    - sensor.date
    - sensor.date_time
    - sensor.moon
    - sensor.next_rising
    - sensor.notification_hour
    - sensor.notification_minute
    - sensor.notification_time
    - sensor.notification_time_long
    - sensor.people_in_space
    - sensor.pws_weather_1n_metric
    - sensor.pws_weather_2d_metric
    - sensor.pws_weather_2n_metric
    - sensor.pws_weather_3d_metric
    - sensor.pws_weather_3n_metric
    - sensor.pws_weather_4d_metric
    - sensor.pws_weather_4n_metric
    - sensor.since_last_boot
    - sensor.time
    - sensor.time_date
    - sensor.yr_high_clouds
    - sensor.yr_low_clouds
    - sensor.yr_medium_clouds