- name: Discoscene
  entities:
    light.spots_tv:
      state: on
      effect: colorloop
      brightness: 200
- name: Romantisch
  entities:
    light.spots_tv:
      state: on
      brightness: 150
      rgb_color: [128, 0, 128]
- name: dimmen
  entities:
    light.spots_tv:
      state: on
      brightness: 50
- name: lezen
  entities:
    light.links_achter:
      state: on
      rgb_color: [255, 255, 255]
      brightness: 255
    light.rechts_achter:
      state: on
      rgb_color: [255, 255, 255]
      brightness: 255
- name: Wit Licht
  entities:
    light.spots_tv:
      state: on
      rgb_color: [255,250,250]
      brightness: 240
# - name: Slaapkamer Random
#   entities:
#     light.slaapkamer:
#       state: on
#       effect: random
#       brightness: 255
- name: RAFC1
  entities:
    light.links_voor:
      state: on
      rgb_color: [255, 255, 255]
      brightness: 255
    light.links_achter:
      state: on
      rgb_color: [206, 21, 55]
      brightness: 255
    light.rechts_achter:
      state: on
      rgb_color: [255, 255, 255]
      brightness: 255
    light.rechts_midden:
      state: on
      rgb_color: [206, 21, 55]
      brightness: 255
    light.rechts_voor:
      state: on
      rgb_color: [255, 255, 255]
      brightness: 255
- name: RAFC2
  entities:
    light.links_voor:
      state: on
      rgb_color: [206, 21, 55]
      brightness: 255
    light.links_achter:
      state: on
      rgb_color: [255, 255, 255]
      brightness: 255
    light.rechts_achter:
      state: on
      rgb_color: [206, 21, 55]
      brightness: 255
    light.rechts_midden:
      state: on
      rgb_color: [255, 255, 255]
      brightness: 255
    light.rechts_voor:
      state: on
      rgb_color: [206, 21, 55]
      brightness: 255
