  ###  Smappee  ###
  - platform: mqtt
    name: "Smappee mqtt Reserve 3"
    icon: mdi:power-socket-eu
    state_topic: "servicelocation/576a42cf-d672-11e7-ac58-022d286959f5/plug/1/state"
    command_topic: "servicelocation/576a42cf-d672-11e7-ac58-022d286959f5/plug/1/setstate"
    value_template: "{{ value_json.value }}"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: "Smappee mqtt Reserve 4"
    icon: mdi:power-socket-eu
    state_topic: "servicelocation/576a42cf-d672-11e7-ac58-022d286959f5/plug/3/state"
    command_topic: "servicelocation/576a42cf-d672-11e7-ac58-022d286959f5/plug/3/setstate"
    value_template: "{{ value_json.value }}"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: "Smappee mqtt Koffiezet"
    icon: mdi:coffee
    state_topic: "servicelocation/576a42cf-d672-11e7-ac58-022d286959f5/plug/4/state"
    command_topic: "servicelocation/576a42cf-d672-11e7-ac58-022d286959f5/plug/4/setstate"
    value_template: "{{ value_json.value }}"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: "Smappee mqtt Opladers"
    icon: mdi:power-socket-eu
    state_topic: "servicelocation/576a42cf-d672-11e7-ac58-022d286959f5/plug/2/state"
    command_topic: "servicelocation/576a42cf-d672-11e7-ac58-022d286959f5/plug/2/setstate"
    value_template: "{{ value_json.value }}"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: "Smappee mqtt Tv"
    icon: mdi:television
    state_topic: "servicelocation/576a42cf-d672-11e7-ac58-022d286959f5/plug/7/state"
    command_topic: "servicelocation/576a42cf-d672-11e7-ac58-022d286959f5/plug/7/setstate"
    value_template: "{{ value_json.value }}"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: "Smappee mqtt Verwarming Bureau"
    icon: mdi:radiator
    state_topic: "servicelocation/576a42cf-d672-11e7-ac58-022d286959f5/plug/8/state"
    command_topic: "servicelocation/576a42cf-d672-11e7-ac58-022d286959f5/plug/8/setstate"
    value_template: "{{ value_json.value }}"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: "Smappee mqtt Kerstverlichting"
    icon: mdi:pine-tree
    state_topic: "servicelocation/576a42cf-d672-11e7-ac58-022d286959f5/plug/9/state"
    state_on: "ON"
    state_off: "OFF"
    command_topic: "servicelocation/576a42cf-d672-11e7-ac58-022d286959f5/plug/9/setstate"
    value_template: "{{ value_json.value }}"
    payload_on: "ON"
    payload_off: "OFF"
    # payload_off: '{"value":"OFF","since":"{{ (as_timestamp(now()) * 1000) | round(0)}}"}'
    # payload_on: '{"value": "ON", "since": {{ (as_timestamp(now()) * 1000) | round(0)}}}'