  - platform: template
    covers:
      keuken_1_temp:
        friendly_name: "Keuken 1"
        value_template: "{{ is_state('input_boolean.keuken_1_closed', 'off')}}"
        open_cover:
          service: script.turn_on
          data:
            entity_id: script.keuken_1_openen
        close_cover:
          service: script.turn_on
          data:
            entity_id: script.keuken_1_sluiten
        stop_cover:
          service: cover.stop_cover
          data:
            entity_id: cover.keuken_1
        # icon_template: >-
        #   {% if states('sensor.garage_door')|float > 0 %}
        #     mdi:garage-open
        #   {% else %}
        #     mdi:garage
        #   {% endif %}

      keuken_2_temp:
        friendly_name: "Keuken 2"
        value_template: "{{ is_state('input_boolean.keuken_2_closed', 'off')}}"
        open_cover:
          service: script.turn_on
          data:
            entity_id: script.keuken_2_openen
        close_cover:
          service: script.turn_on
          data:
            entity_id: script.keuken_2_sluiten
        stop_cover:
          service: cover.stop_cover
          data:
            entity_id: cover.keuken_2
        # icon_template: >-
        #   {% if states('sensor.garage_door')|float > 0 %}
        #     mdi:garage-open
        #   {% else %}
        #     mdi:garage
        #   {% endif %}

      zonnetent_temp:
        friendly_name: "Zonnetent"
        value_template: "{{ is_state('input_boolean.zonnetent_closed', 'off')}}"
        open_cover:
          service: script.turn_on
          data:
            entity_id: script.zonnetent_openen
        # close_cover:
        #   service: script.turn_on
        #   data:
        #     entity_id: script.zonnetent_sluiten
        close_cover:
          service: script.turn_on
          data:
            entity_id: script.zonnetent_my
        # icon_template: >-
        #   {% if states('sensor.garage_door')|float > 0 %}
        #     mdi:garage-open
        #   {% else %}
        #     mdi:garage
        #   {% endif %}

      living_temp:
        friendly_name: "Living"
        value_template: "{{ is_state('input_boolean.living_closed', 'off')}}"
        open_cover:
          service: script.turn_on
          data:
            entity_id: script.living_openen
        close_cover:
          service: script.turn_on
          data:
            entity_id: script.living_sluiten
        stop_cover:
          service: cover.stop_cover
          data:
            entity_id: cover.living
        # icon_template: >-
        #   {% if states('sensor.garage_door')|float > 0 %}
        #     mdi:garage-open
        #   {% else %}
        #     mdi:garage
        #   {% endif %}

      slaapkamer_temp:
        friendly_name: "Slaapkamer"
        value_template: "{{ is_state('input_boolean.slaapkamer_closed', 'off')}}"
        open_cover:
          service: script.turn_on
          data:
            entity_id: script.slaapkamer_openen
        close_cover:
          service: script.turn_on
          data:
            entity_id: script.slaapkamer_sluiten
        stop_cover:
          service: cover.stop_cover
          data:
            entity_id: cover.slaapkamer
        # icon_template: >-
        #   {% if states('sensor.garage_door')|float > 0 %}
        #     mdi:garage-open
        #   {% else %}
        #     mdi:garage
        #   {% endif %}

      slaapkamer_noor_temp:
        friendly_name: "Slaapkamer Noor"
        value_template: "{{ is_state('input_boolean.slaapkamer_noor_closed', 'off')}}"
        open_cover:
          service: script.turn_on
          data:
            entity_id: script.slaapkamer_noor_openen
        close_cover:
          service: script.turn_on
          data:
            entity_id: script.slaapkamer_noor_sluiten
        stop_cover:
          service: cover.stop_cover
          data:
            entity_id: cover.slaapkamer_noor
        # icon_template: >-
        #   {% if states('sensor.garage_door')|float > 0 %}
        #     mdi:garage-open
        #   {% else %}
        #     mdi:garage
        #   {% endif %}