  tvpi_retain_0:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'monitor/tvPi/bompa'
          retain: true
          payload_template: "{\"confidence\":\"0\", \"type\":\"retained from away\"}"
      - service: mqtt.publish
        data_template:
          topic: 'monitor/tvPi/oma'
          retain: true
          payload_template: "{\"confidence\":\"0\", \"type\":\"retained from away\"}"
      - service: mqtt.publish
        data_template:
          topic: 'monitor/tvPi/gphone'
          retain: true
          payload_template: "{\"confidence\":\"0\", \"type\":\"retained from away\"}"
      - service: mqtt.publish
        data_template:
          topic: 'monitor/tvPi/mphone'
          retain: true
          payload_template: "{\"confidence\":\"0\", \"type\":\"retained from away\"}"