- platform: mqtt
  state_topic: 'monitor/scan/arrive'
  # value_template: "{{ value_json.identity }}"
  # expire_after: 60
  name: Aankomst

- platform: mqtt
  state_topic: 'monitor/scan/depart'
  # value_template: "{{ value }}"
  # expire_after: 60
  name: Vertrek

# - platform: mqtt
#   state_topic: 'monitor/Garage/status'
#   # state_topic: 'monitor/heartbeat/Garage'
#   # value_template: '{{ value_json.identity }}'
#   expire_after: 60
#   icon: mdi:heart-pulse
#   name: Heartbeat Garage

# - platform: mqtt
#   state_topic: 'monitor/Living/status'
#   # state_topic: 'monitor/heartbeat/Living'
#   # value_template: '{{ value_json.identity }}'
#   expire_after: 60
#   icon: mdi:heart-pulse
#   name: Heartbeat Living

# - platform: mqtt
#   state_topic: 'monitor/Keuken/status'
#   # state_topic: 'monitor/heartbeat/Keuken'
#   # value_template: '{{ value_json.identity }}'
#   expire_after: 60
#   icon: mdi:heart-pulse
#   name: Heartbeat Keuken
