- platform: mqtt
  name: "Garage throttle"
  state_topic: "Garage/system/throttle"
  payload_off: "false"
  payload_on: "true"
  availability_topic: "Garage/status"
  payload_available: "online"
  payload_not_available: "offline"
  device_class: problem

- platform: mqtt
  name: "Garage undervoltage"
  state_topic: "Garage/system/undervoltage"
  payload_off: "false"
  payload_on: "true"
  availability_topic: "Garage/status"
  payload_available: "online"
  payload_not_available: "offline"
  device_class: problem

- platform: mqtt
  name: "Garage online"
  state_topic: "Garage/status"
  payload_off: "offline"
  payload_on: "online"
  availability_topic: "Garage/status"
  payload_available: "online"
  payload_not_available: "offline"
  device_class: connectivity
  off_delay: 75

- platform: template
  sensors:
    nodered_garage_down:
      friendly_name: "NodeRed unavailable"
      device_class: problem
      value_template: >-
        {{ states("sensor.buitentemperatuur") == 'unavailable'}}
