  - platform: template
    sensors:

    #----- Count Automations
      count_automations:
        entity_id: sensor.date
        value_template: "{{ states.automation | list | length }}"

    #----- Count Scripts
      count_scripts:
        entity_id: sensor.date
        value_template: "{{ states.script| list | length }}"

    #----- Count Device Trackers
      count_device_trackers:
        entity_id: sensor.date
        value_template: "{{ states.device_tracker | list | length }}"

    #----- Count Binary Sensors
      count_binary_sensors:
        entity_id: sensor.date
        value_template: "{{ states.binary_sensor| list | length }}"

    #----- Count Sensors
      count_sensors:
        entity_id: sensor.date
        value_template: "{{ states.sensor | list | length }}"

    #----- Count Switches
      count_switches:
        entity_id: sensor.date
        value_template: "{{ states.switch | list | length }}"

    #----- Count Zones
      count_zones:
        entity_id: sensor.date
        value_template: "{{ states.zone | list | length }}"

    #----- Input Booleans
      count_input_booleans:
        entity_id: sensor.date
        value_template: "{{ states.input_boolean | list | length }}"

    #----- Input Numbers
      count_input_numbers:
        entity_id: sensor.date
        value_template: "{{ states.input_number | list | length }}"

    #----- Input Texts
      count_input_texts:
        entity_id: sensor.date
        value_template: "{{ states.input_text | list | length }}"

    #----- Input Selects
      count_input_selects:
        entity_id: sensor.date
        value_template: "{{ states.input_select | list | length }}"

    #----- Input Date Times
      count_input_datetimes:
        entity_id: sensor.date
        value_template: "{{ states.input_datetime | list | length }}"