  - platform: template
    sensors:
      temp_living:
        value_template: "{{ states.climate.netatmo_living.attributes.current_temperature }}"
        unit_of_measurement: 'Â°C'

      verwarming_beneden:
        # value_template: "{{states.climate.netatmo_living.attributes.operation_mode}}"
        # value_template: "{{states.climate.netatmo_living.attributes.boiler_status}}"
        value_template: "{{states.climate.netatmo_living.attributes.hvac_action}}"

      binnen_vs_buiten:
        value_template: >-
              {% if (states('sensor.gemiddelde_temp_binnen')) > (states('sensor.gemiddelde_temp_buiten')) and states('sensor.gemiddelde_temp_binnen') | float > 26 %}
                 Afkoeling
              {% else %}
                 Geen afkoeling
              {% endif %}

      bathroom_humidity_change_template:
        friendly_name: "Badkamer luchtvochtigheid verandering"
        icon_template: mdi:water-percent
        value_template: >-
          {{ states.sensor.badkamer_luchtvochtigheid_stats.attributes.change | float }}
      
      bathroom_humidity_change_template_percent:
        friendly_name: "Badkamer luchtvochtigheid verandering"
        icon_template: mdi:water-percent
        unit_of_measurement: '%'
        value_template: >-
          {{ states.sensor.badkamer_luchtvochtigheid_stats.attributes.change | float }}

      keuken_humidity_change_template:
        friendly_name: "Keuken luchtvochtigheid verandering"
        icon_template: mdi:water-percent
        value_template: >-
          {{ states.sensor.keuken_luchtvochtigheid_stats.attributes.change | float }}
      
      keuken_humidity_change_template_percent:
        friendly_name: "Keuken luchtvochtigheid verandering"
        icon_template: mdi:water-percent
        unit_of_measurement: '%'
        value_template: >-
          {{ states.sensor.keuken_luchtvochtigheid_stats.attributes.change | float }}