  - platform: template
    sensors:
      sonos_artist:
        friendly_name: Sonos Keuken artiest
        icon_template: mdi:microphone-variant
        value_template: >-
          {{ state_attr("media_player.keuken", "media_artist") }}