  - platform: template
    sensors:
      beta_gps_accuracy:
        value_template: "{{ state_attr('device_tracker.gphone_2', 'gps_accuracy') }}"
        unit_of_measurement: 'm'
      beta_gps_accuracy_m:
        value_template: "{{ state_attr('device_tracker.mphone_2', 'gps_accuracy') }}"
        unit_of_measurement: 'm'
      bay_probability:
        value_template: "{{ state_attr('binary_sensor.giel_bayesian', 'probability') }}"
        # unit_of_measurement: 'm'
      bay_observations:
        value_template: "{{ state_attr('binary_sensor.giel_bayesian', 'observations') }}"
        # unit_of_measurement: 'm'
      # 1_5_1_gps_accuracy:
      #   value_template: "{{ state_attr('device_tracker.gphone_1_5', 'gps_accuracy') }}"
      #   unit_of_measurement: 'm'
      # 1_5_1_trigger:
      #   value_template: "{{ state_attr('device_tracker.gphone_1_5', 'gps_accuracy') }}"
        