  rafc1_2:
    sequence:
      - service: light.turn_on
        data:
          rgb_color: [255, 255, 255]
          brightness: 255
          entity_id:
            - light.rechts_midden
            - light.links_achter
      - delay:
         seconds: 2
      - service: light.turn_on
        data:
          rgb_color: [255, 255, 255]
          brightness: 255
          entity_id:
            - light.rechts_achter
            - light.links_voor
      - service: light.turn_on
        data:
          rgb_color: [206, 21, 55]
          brightness: 255
          entity_id:
            - light.rechts_midden
            - light.links_achter
      - delay:
         seconds: 2
      - service: light.turn_on
        data:
          rgb_color: [255, 255, 255]
          brightness: 255
          entity_id:
            - light.links_achter
            - light.rechts_voor
      - service: light.turn_on
        data:
          rgb_color: [206, 21, 55]
          brightness: 255
          entity_id:
            - light.rechts_achter
            - light.links_voor
      - delay:
         seconds: 2
      - service: light.turn_on
        data:
          rgb_color: [255, 255, 255]
          brightness: 255
          entity_id:
            - light.links_voor
            - light.rechts_midden
      - service: light.turn_on
        data:
          rgb_color: [206, 21, 55]
          brightness: 255
          entity_id:
            - light.links_achter
            - light.rechts_voor
      - delay:
         seconds: 2
      - service: light.turn_on
        data:
          rgb_color: [255, 255, 255]
          brightness: 255
          entity_id:
            - light.rechts_voor
            - light.rechts_achter
      - service: light.turn_on
        data:
          rgb_color: [206, 21, 55]
          brightness: 255
          entity_id:
            - light.links_voor
            - light.rechts_midden
      - delay:
         seconds: 2
      - service: script.rafc1_1
