  rafc2_1:
    sequence:
      - service: light.turn_on
        data:
          rgb_color: [255, 255, 255]
          brightness: 255
          entity_id:
            - light.rechts_midden
      - delay: 
         seconds: 8
      - service: light.turn_on
        data:
          rgb_color: [255, 255, 255]
          brightness: 255
          entity_id:
            - light.rechts_achter
      - service: light.turn_on
        data:
          rgb_color: [206, 21, 55]
          brightness: 255
          entity_id:
            - light.rechts_midden
      - delay:
         seconds: 8
      - service: light.turn_on
        data:
          rgb_color: [255, 255, 255]
          brightness: 255
          entity_id:
            - light.links_achter
      - service: light.turn_on
        data:
          rgb_color: [206, 21, 55]
          brightness: 255
          entity_id:
            - light.rechts_achter
      - delay:
         seconds: 8
      - service: light.turn_on
        data:
          rgb_color: [255, 255, 255]
          brightness: 255
          entity_id:
            - light.links_voor
      - service: light.turn_on
        data:
          rgb_color: [206, 21, 55]
          brightness: 255
          entity_id:
            - light.links_achter
      - delay:
         seconds: 8
      - service: light.turn_on
        data:
          rgb_color: [255, 255, 255]
          brightness: 255
          entity_id:
            - light.rechts_voor
      - service: light.turn_on
        data:
          rgb_color: [206, 21, 55]
          brightness: 255
          entity_id:
            - light.links_voor
      - delay:
         seconds: 8
      - service: light.turn_on
        data:
          rgb_color: [206, 21, 55]
          brightness: 255
          entity_id:
            - light.rechts_voor
      - service: script.rafc2_2
