
  setpunt_noor:
    name: Setpunt Noor
    options:
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
    initial: 17

  setpunt_fien:
    name: Setpunt Fien
    options:
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
    initial: 17

  setpunt_badkamer:
    name: Setpunt Badkamer
    options:
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
    initial: 19

  setpunt_slaapkamer:
    name: Setpunt Slaapkamer
    options:
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
    initial: 17
